### ISSUE TITLE
[Design Thread - User Profile]  Enhance User Profile (Mobile/Desktop) Public Viewing Profile & User modifying Profile

### ISSUE THREAD

**Issue by ri0nardo** [waterthetrees/wtt_front#300]
To have two designs for profiles per use of platform.
One for desktop
One for mobile
- Design for public profile viewing
- Design for user editing / viewing public profile
  - To be similar, but the user will have more commands and actions to edit / modify content within their profile.
- See YouTube channels as an example of how long a channel has been there.
- Have the ability to search for users from a search engine as well?
- See link for table and grid https://mui.com/x/react-data-grid/

**Enhancements**

- [x] Prioritize user info from name to email
- Name
- User Name?
- Email (If user wants it public)
- Social Medias
- Phone Number (If user wants it public)
- [x] Show adopted trees, for personal view have the maintenance feature available to edit each tree.
- [x] A Title you given yourself
- Tree Care
- Engineer
- Flower Expert
- [x] Add a bio
- Show it have a character limit?
- Show it be unlimited text?
- [x] Add message/email button or call it contact info
- Message
- Contact Info
- [x] Cover Photo for Profile
- The Hero Image
- [x] Add data on how many trees planted, photos taken, and followers
- [x] Add location
- Can be the specific location
- Can be a general area (ex: San Francisco Bay Area)
- Can be disabled for privacy reasons
- [x] Tree Table Enhancement (Build off the existing table)
- Design the user table
- Design viewer tree table
 - Future Design to add to the Trees
   - List if the tree is part of an organization
   - List multiple owners if has more than 1
   - Original date planted
   - Awards
   - Past names
- [x] Invite friend through email / text (See issue #215 ) (NEEDS ENGINEER TO BUILD OUT)
- Design Graphic for Invite Friend
- [x] Design Weather Section Right Column (See issue #321 ) (NEEDS ENGINEER TO BUILD OUT)
- To have 4 scenarios
  - [x] Sunny
  - [ ] Cloudy
  - [ ] Rainy
  - [ ] Night
- [x] Report Bug (FUTURE PLANS / COMING SOON) (See Issue #304 )
- Design a lady bug to add to report bug
- Redirect users to report bug page
- [x] Have upcoming events / calendar events show up on the right column (FUTURE PLANS / COMING SOON) (See Issue #272 ) 
- Be color coded per event type
- [ ] Add badges (FUTURE PLANS / COMING SOON) #287 
- [ ] Add a follow/add friend button (FUTURE PLANS / COMING SOON)
- [ ] Show any organizations they are part of (FUTURE PLANS / COMING SOON) wtt_front #267 
- https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile
- [ ] Have default images for users to pick from (Design generic profile icons) (FUTURE PLAN)
- https://support.mightycause.com/hc/en-us/articles/360031005092-How-to-Make-Your-Giving-Event-Profile-Awesome
- [ ] Add how long the user has been a member (FUTURE PLANS / COMING SOON)
- Do we just add the year?
- The specific date?
- Months?
- Have this disabled for people who want it private?
- [ ] Add interest (FUTURE PLAN)
- Interest can be a category related to trees or unrelated
- Can be a person who is an arborist
- Can say interest is music
- Cooking
- Dogs
- [ ] Photos Taken (FUTURE PLAN)
- Can create folders of types
- Favorites

**Add Sections or tabs in profile**

- [ ] Trees adopted
- [ ] Comments / Reviews (FUTURE PLANS / COMING SOON)
- [ ] Photos Taken (FUTURE PLANS / COMING SOON)
- [ ] Followers (FUTURE PLANS / COMING SOON)
- [ ] Badges owned (FUTURE PLANS / COMING SOON) #287 
- [ ] Checked in locations (FUTURE PLANS / COMING SOON)
- [ ] Organizations associated with (FUTURE PLANS / COMING SOON) #267 

![Image](https://user-images.githubusercontent.com/98299952/196071660-b6a72ae8-ea9d-413d-857c-504298a16a1b.jpg)

**Comment by saimaheshtaduri** [comment]
I can contribute. Assign me @ri0nardo

**Comment by ri0nardo** [comment]
@saimaheshtaduri hi will you be able to work on this issue?

**Comment by ri0nardo** [comment]
@jazhen @zoobot Started the redesign for the user profile. I am following the theme that was developed from the about us & contact us redesign.

Sort of alot going on that is new, but new fun things have been implemented. 

- Wanted your thoughts on the data where the cover photo is.
- The weather report on the top right.
- Having a public profile where people can come view what you did & a personal profile view where you can edit info.
- I reorganized the table for trees. I wanted to limit the specificity of each category and bunch them.
- Lastly, what do you think of the lady bug for reporting a bug? Thought it was a more appropriate bug people can feel comfortable with rather than a cockroach or other insects.
![Personal Profile View](https://user-images.githubusercontent.com/98299952/196354048-1c35d6a9-7f93-4ca8-b007-ecac919a2cd6.jpg)
![Public Profi
![Edit Mode](https://user-images.githubusercontent.com/98299952/196354066-fe1a3f90-5e46-477b-9830-6071262e6c9c.jpg)
le View](https://user-images.githubusercontent.com/98299952/196354061-711b6784-f319-4ed9-b840-ff19e82ee5c3.jpg)

**Comment by ri0nardo** [comment]
Note from 10/19/2022 meeting:

- [ ] Jason comments how does the table adapt to mobile?
- [ ] Jason comments how does the tree info bar come into play when a user wants to view details regarding their tree? Either goes to the map or the side bar comes out where the right column is. If sidebar appears, needs a button to go to map where the tree is.

**Comment by ri0nardo** [comment]
Will proceed with a personal view of the profile. Public view of a profile will come later on once other things get implemented to have that option. The right column is not going to be implemented soon since the software isn't built out yet or hasn't even started.
Will need to clean up the tree table to proceed and be built.

**Comment by zoobot** [comment]
@ri0nardo I think these sidebar things are all somewhat easy to do. We could maybe have them as separate widgets/issues as quick tasks for newcomers to do first. 

Report a bug can be a form that connects to our git issues via api or to start with either sends an email to us. MVP of sending an email is simple and good first  issue Widget.

Plant with friends is feasible just to open an email or share on social. Good first issues Widget for newcomers.

Perform maintenance on trees in my backyard could potentially just go to the map and use geolocation to go the user's location. the code for geolocation already works and we are using it for planting trees so would be simple to tie into that.

The only one that might take more work is weather but that is a good first issue for backend engineers. They could potentially link into the weather api which is a pretty simple api to work with.

**Comment by zoobot** [comment]
So your design's not blocked, maybe the sidebar widgets could have placeholder tree images?

**Comment by ri0nardo** [comment]
@zoobot the column with weather etc would bring up the tree info sidebar. If the user wanted to do maintenance from their profile they could bring up all the info there. So no need for a placeholder tree image. It was a good suggestion by jason.

**Comment by ri0nardo** [comment]
@zoobot would potentially look like the image below.
![Desktop - 15](https://user-images.githubusercontent.com/98299952/205214294-d3e0f849-01eb-43af-bd9b-2482dd64721b.jpg)

**Comment by zoobot** [comment]
Good idea Jason! Looks great

**Comment by ri0nardo** [comment]
Mobile view. 

![Image](https://user-images.githubusercontent.com/98299952/205846548-1b9db0c9-72fc-402b-85b0-837ea5d9fd20.jpg)

**Comment by ri0nardo** [comment]
![1_Tt2x8SRugOlJQNsMdidF_g](https://user-images.githubusercontent.com/98299952/206100793-1b5a0e8c-2d3a-4da2-b136-fe5aa4840e48.gif)

**Comment by zoobot** [comment]
@Domingo-creator Are you still working on implementing the new user design?

**Comment by ri0nardo** [comment]
I am reconsidering the design for the user profile. I am looking at a previous design from someone else that was working on this project and found a solution that may work better than what I currently designed for the user profile.

This list all the trees and you would click the tree to see the tree history rather than using a table. I do like this idea and want to take this further with the design I did have in place. The table does work on desktop, but for mobile it not ideal. 

@zoobot what do you think of this previous design? I would have to revise and iterate on it to fit what I designed, but I do like this idea.



![Image](https://user-images.githubusercontent.com/98299952/223284263-e48d11b5-026b-4111-bd37-3c7ade7fa832.jpg)
![Image](https://user-images.githubusercontent.com/98299952/223284266-84e1e02c-4843-4b49-8e4b-6a235873df3d.jpg)

**Comment by ri0nardo** [comment]
will update with mobile being a focus (not an after thought)
will have 3 main sections
- trees
- achievements
- organizations
will be a tab sections with trees being the default.
will reuse the redesign profile section and use a previous design from someone else for the sections.
will add separate sections below the tabs, for other things related to a user profile.

**Comment by ri0nardo** [comment]
currently liking this redesign that is mobile first. Its tab based where the default is trees. For the future we will have badges and organization list if needed (teams may not be that great of a use in this case).
I want to change the user tags, currently its
- Name
- User type
- Location

I want to change it to
- Name
- Member since
- N/A
The last one I dont really know what is really important.

Rather than listing the tree history with a table and checkbox, we can just create a list / box component of what maintenance was performed. Similar to what the tree history is. I dont want to have the color anymore, Ill want it to be more generic to begin with.



![Image](https://user-images.githubusercontent.com/98299952/230710372-29e06353-085a-4b7d-a4b9-6ebcae97cc14.jpg)
![Image](https://user-images.githubusercontent.com/98299952/230710371-b155c2d0-cefa-4770-9dcf-74402d54a82e.jpg)
![Image](https://user-images.githubusercontent.com/98299952/230710370-977f609e-65c6-4d9b-8681-406d9f08c675.jpg)
