### ISSUE TITLE
[Epic - Tree Taxonomy] Create filterable Tree list based off tree-taxonomy and city street tree tree-allow lists

### ISSUE THREAD

**Issue by zoobot** [waterthetrees/wtt_front#569]
### Quick summary
FUF (Friends of the Urban Forest) has requested a tree taxonomy for the neighborhoods of San Francisco for users to see what trees are acceptable to be planted. Depending on the neighborhood and area, certain trees are restricted due to the climate and amount of sunlight received. The tree taxonomy will serve as a database for all communities plus a source for users to research what tree they may be interested in learning or planting in their neighborhood.

### Issues
A few issues include not having enough source data at the moment for people to see an extensive list of trees. Another issue is the mobile aspect of the product not being as responsive with text clipping or being difficult to read. We want cities to eventually be able to upload or update their data source to have a current source at all times.

### Goal
The goal is to have a responsive product that is viable for all userbases from city government to a random person running into the webpage. And to meet the standards of FUF for requesting the feature.

### Get Started
Get started with our onboarding, https://github.com/waterthetrees/waterthetrees/wiki/Onboarding and read through this epic.

### Resources
- Design Figma: https://www.figma.com/file/5C3v1LUNwMPQy9JOgnKEtr/Water-the-Trees?node-id=1355%3A9085
- Casey Trees https://caseytrees.org/trees-list/

### MVP
- [x] [Image Downloader](https://github.com/waterthetrees/wtt_front/pull/652)
- [x] [View Toggle](https://github.com/waterthetrees/wtt_front/pull/649)
- [x] [Tags for Dormancy](https://github.com/waterthetrees/wtt_front/pull/651)
- [x] [Quilt View Cards](https://github.com/waterthetrees/wtt_front/pull/650)
- [ ] [Column view and Quilt View](https://github.com/waterthetrees/wtt_front/pull/687)

### V1
-[ ] 3 views including Card, List, Column Views
-[ ] Filters show on top for mobile - sticky with ability to x them off the filter list
-[ ] Tree matched count
-[ ] Move the filters back to the left.
-[ ] Have blank image for tree placeholder or find images for every single tree in list
- [ ] Scale images for performance

### Milestone 0 - Design / Preparation
- [x] #617
- [ ] [Tree Taxonomy - Planning] User Flow
- [x] #616
- [ ] #571 
- [x] #619
- [x] #570 
- [ ] #690
- [x] #691
- [ ] [Tree Taxonomy - Design] List Cards Hover Effect
- [ ] [Tree Taxonomy - Design] Table Row Hover Effect
- [ ] [Tree Taxonomy - Design] Component Actions (Mobile / Desktop)
- [ ] [Tree Taxonomy - Design] Sticky Filter (Mobile)
- [ ] [Tree Taxonomy - Design] Sticky Unique Trees

### Milestone 1 - Continuation of Design / Implementation
- [x] #674
- [x] #675
- [x] #676
- [ ] #679
- [x] #680
- [ ] [Tree Taxonomy - Design] Display Type Dropdown Menu
- [x] #681

### Milestone ??? - Future Plans / Ideas

- [ ] AI generated, drawings, or vector/line drawing style images for the trees similar to a simplified cartoon version of [Architecture of Trees](https://papress.com/products/the-architecture-of-trees) and [Ernst Haeckel](https://freevintageillustrations.com/ernst-haeckel-illustrations/) for the tree list page
- [ ] photo gallery of tree species for tree page
- [ ] Build a tree-taxonomy table to host all unique world trees and show native trees per area and link to allowed trees per city
- [ ] [Tree Taxonomy - Planning] Integrate with Map search to show tree cards
- [ ] [Tree Taxonomy - Design] Compare trees with one another by selecting
- [ ] [Tree Taxonomy - Design] QR Generator / Physical Card Design

### Extras
If you have any additional questions just @zoobot

**Comment by zoobot** [comment]
MVP snapshots

<img width="960" alt="Screen Shot 2023-03-17 at 1 36 21 PM" src="https://user-images.githubusercontent.com/22104001/226035413-b94fab4b-eb5c-47df-a461-a1c7da94bba7.png">
<img width="974" alt="Screen Shot 2023-03-17 at 1 36 52 PM" src="https://user-images.githubusercontent.com/22104001/226035598-e7bc14ee-9568-458d-ac1e-3fba4f94d3fe.png">

**Comment by ri0nardo** [comment]
@zoobot do we want to add a task for a search bar?

**Comment by zoobot** [comment]
We have a search bar we can re-use on this component so that probably won't take much work to add in.

We'll need to request the neighborhood list from FUF, to see which trees are allowed in which neighborhoods.

**Comment by ri0nardo** [comment]
Making a note to make this design be mobile compatible.

**Comment by zoobot** [comment]
Mobile view so far, the filter is fixed, the list scrolls.

<img width="353" alt="Screen Shot 2023-03-17 at 7 50 13 PM" src="https://user-images.githubusercontent.com/22104001/226080492-0f4ec08c-5f02-4099-8426-915052f3af2d.png">

**Comment by zoobot** [comment]
Neighborhoods will probably have to be a dropdown.

**Comment by ri0nardo** [comment]
@zoobot looking at the casey trees. the filter being on the top rather than taking up half the screen on the side probably makes more sense for mobile. Adding screenshots. But there could be other solutions as in having a sticky filter at the bottom of the screen to pull up (may not be a good solution, but something I thought of). 
<img width="294" alt="mobile filter" src="https://user-images.githubusercontent.com/98299952/226081021-8509f00a-6151-4921-924b-2ca26a148617.PNG">
<img width="291" alt="mobile filter dropdown" src="https://user-images.githubusercontent.com/98299952/226081022-883a6ce6-7e8e-458c-884d-1821e0d77d47.PNG">

**Comment by zoobot** [comment]
It's using the Slideout Drawer for the sidebar filter so for mobile we'd have to switch to the Scrollable Dialogue component for the filter to be full screen. Should be an easy change for that.

**Comment by ri0nardo** [comment]
@zoobot Wanted to make this suggestion, not for the mvp, but a later integration. I was considering integrating this filter onto the map page rather than its own. You mentioned that FUF want to base this off neighborhoods, and identifying the neighborhood for 2/3 of the screen would be a nice touch if we highlight the boundary. 
![Desktop View](https://user-images.githubusercontent.com/98299952/226420578-7378f4e4-aea4-45dc-909f-58b4d2464eec.jpg)

**Comment by zoobot** [comment]
Great idea @ri0nardo This would be a very nice filter to have. 

I am going to add @tzinckgraf on this as we'd need more data to be in the vector tiles to do this kind of filtering on the map. 

Since FUF also wanted to use it to give homeowners a way to choose a good tree, might be nice to have it 
1. On it's own treeinfo page with a button to show the map as well
2. On the map with a revamp of the current filter
3. Integrated into in the planting request somehow?

**Comment by ri0nardo** [comment]
@zoobot a few more questions about the tree taxonomy. Since each tree is a card, do we want to add tags to each tree? I ask since the casey trees have less content when presented. 
The mock up you made has quite alot more content, but only show 3 full cards and 3 partial cards. On the https://caseytrees.org/trees-list/ you see about 15 cards on desktop which is quite alot. Not sure which direction we want to go if its more content on the preview or more cards presented.
Also you mention requesting trees, I assume we will have trees that will be allowable per neighborhood or city. Are we going to make it so users need an account to request any tree or maintenance? I went on this cities request form and it doesnt require an account or email when making any type of request https://www.chulavistaca.gov/departments/public-works/service-requests . doesnt allow you to request a tree, but just mentioning that.

**Comment by zoobot** [comment]
since that version, I removed the notes and only have that on the tree's page. We can squish it down to fit more cards. Tags would be nice, what would go on there? 
We should start making a list of ALL the stuff that would be nice to have on there and then we can trim it down to MVP.

We don't actually have the data for which trees are allowed in which neighborhoods/city so that'll have to be city by city. We should brainstorm how we can make that easier.

It is nice to be able to request without having to make an account. I am on the fence on this one.

**Comment by zoobot** [comment]
List of data on the cards: (feel free to edit/add to this list)

- drought tolerant
- Watering needs
- native
- flowering
- growth speed
- sun/shade/partial shade


https://calscape.org/loc-California/Sambucus-mexicana-(Blue-Elderberry)?srchcr=sc642110e4ac778

**Comment by ri0nardo** [comment]
A tag I was thinking of was neighborhood, but that now seems too specific since we might run into multiple Financial districts throughout many cities. But maybe a nice tag is whether the tree is endangered? I haven't gave it much thought. I've just notice that tags are good for cards to give quick info that is eye catching.

**Comment by zoobot** [comment]
Sounds good, we could have leaf badges too

**Comment by ri0nardo** [comment]
@zoobot since there is unique tree data, is there going to be an upload that is similar to the sources?

**Comment by zoobot** [comment]
> @zoobot since there is unique tree data, is there going to be an upload that is similar to the sources?

Good idea! These files tend to be pretty big. Our current code relies on a build process when the server starts so we need to think through whether we want to host the files or link to a url somewhere. Not sure how common it is to share these types of files via the web... This should be a v1 feature, not mvp.

**Comment by ri0nardo** [comment]
> Good idea! These files tend to be pretty big. Our current code relies on a build process when the server starts so we need to think through whether we want to host the files or link to a url somewhere. Not sure how common it is to share these types of files via the web... This should be a v1 feature, not mvp.

If its not common to share the files then its not worth the time trying to build this out?

**Comment by zoobot** [comment]
> If its not common to share the files then its not worth the time trying to build this out?

Every city I've talked to has a "list per neighborhood" and they email it to users when you ask. I meant I'm not sure how often they host it as city open data so we can grab a url or will we have to just save their csv.
